### ISSUE TITLE
Некорректное отображение изображений в формате .bmp

### ISSUE THREAD

**Issue by Ivan-Veselov** [CardBoardGame9000/cbg-platform#1]
Если во время редактирования карты попытаться создать новый слой типа "изображение" и загрузить в качестве изображения картинку в формате .bmp, то редактор изобразит вместо картинки случайный шум.

0. Коммит 0c2a132cfb1823419a05470aca71523e6ec3de8b
1. Открыть произвольную карту для редактирования
2. Слои -> Новый слой-изображение
3. Выбрать картинку в формате .bmp
4. На новом слое будет отрисовываться цветовой шум, а не та картинка, которая загружалась.

**Comment by demarkok** [comment]
#6
